# Generated by Django 4.0.1 on 2022-01-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_nse_bse_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='nse_bse_dividend_alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_ticker', models.CharField(max_length=254)),
                ('dividend_type', models.CharField(max_length=254)),
                ('dividend_precentage', models.CharField(max_length=254)),
                ('date_announcement', models.CharField(max_length=254)),
                ('date_record', models.CharField(max_length=254)),
                ('ex_dividend_date', models.CharField(max_length=254)),
            ],
        ),
    ]
